import{a as v,S as q,i as n}from"./assets/vendor-Db2TdIkw.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function a(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=a(t);fetch(t.href,s)}})();async function h(e,r=1){const a={key:"49512194-f753c2f34a7e7dbbd609db53f",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};return await v.get("https://pixabay.com/api/",{params:a})}function g(e,r){const a=r.map(o=>`<li class="gallery-item">
    <a class="image-link" href="${o.largeImageURL}"><img class="image" src="${o.webformatURL}" alt="${o.tags}" title=""/></a>
    <ul class="image-descr-list">
<li class="descr-item">Likes<span class="descr-span">${o.likes}</span></li>
<li class="descr-item">Views<span class="descr-span">${o.views}</span></li>
<li class="descr-item">Comments<span class="descr-span">${o.comments}</span></li>
<li class="descr-item">Downloads<span class="descr-span">${o.downloads}</span></li>
    </ul>
    </li>`).join("");e.insertAdjacentHTML("beforeend",a),S()}const w=new q(".gallery-item a",{captionsData:"alt",captionDelay:250});function S(){w.refresh()}function B(e){e.innerHTML=""}function b(){const e=document.querySelector(".loader");e.style.display="flex"}function d(){const e=document.querySelector(".loader");e.style.display="none"}function L(){document.querySelector(".load-more-btn").classList.remove("visually-hidden")}function u(){document.querySelector(".load-more-btn").classList.add("visually-hidden")}const m=document.querySelector(".gallery"),y=document.querySelector(".form"),f=y.elements[0];f.classList.add("input");const M=y.elements[1];M.classList.add("button");const R=document.querySelector(".load-more-btn");let l=null,p=null,i=null;y.addEventListener("submit",P);function P(e){if(e.preventDefault(),B(m),u(),b(),i=f.value,l=1,i===""){d(),n.error({message:"Write your something you want to see",position:"topRight"});return}h(i,l).then(r=>{if(r.data.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),u();return}else{g(m,r.data.hits);let o=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o.height*2,behavior:"smooth"}),p=Math.ceil(r.data.totalHits/15),l<p?L():n.info({position:"bottomCenter",message:"We're sorry, but you've reached the end of search results."})}}).catch(()=>{n.error({message:"Bad request",position:"topRight"})}).finally(()=>{d(),f.value=""})}R.addEventListener("click",e=>{e.preventDefault(),u(),b(),l+=1,h(i,l).then(r=>{g(m,r.data.hits);let o=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o.height*2,behavior:"smooth"}),l<p?L():n.info({position:"bottomCenter",message:"We're sorry, but you've reached the end of search results."})}).catch(()=>{n.error({message:"Bad request",position:"topRight"})}).finally(()=>{d()})});
//# sourceMappingURL=index.js.map
