import{a as w,S as v,i as n}from"./assets/vendor-Db2TdIkw.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))r(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&r(c)}).observe(document,{childList:!0,subtree:!0});function a(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(o){if(o.ep)return;o.ep=!0;const s=a(o);fetch(o.href,s)}})();async function g(e,t=1){const a={key:"49512194-f753c2f34a7e7dbbd609db53f",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return await w.get("https://pixabay.com/api/",{params:a})}function h(e,t){const a=t.map(r=>`<li class="gallery-item">
    <a class="image-link" href="${r.largeImageURL}"><img class="image" src="${r.webformatURL}" alt="${r.tags}" title=""/></a>
    <ul class="image-descr-list">
<li class="descr-item">Likes<span class="descr-span">${r.likes}</span></li>
<li class="descr-item">Views<span class="descr-span">${r.views}</span></li>
<li class="descr-item">Comments<span class="descr-span">${r.comments}</span></li>
<li class="descr-item">Downloads<span class="descr-span">${r.downloads}</span></li>
    </ul>
    </li>`).join("");e.insertAdjacentHTML("beforeend",a),S()}const q=new v(".gallery-item a",{captionsData:"alt",captionDelay:250});function S(){q.refresh()}function B(e){e.innerHTML=""}function b(){const e=document.querySelector(".loader");e.style.display="flex"}function d(){const e=document.querySelector(".loader");e.style.display="none"}function L(){document.querySelector(".load-more-btn").classList.remove("visually-hidden")}function u(){document.querySelector(".load-more-btn").classList.add("visually-hidden")}const m=document.querySelector(".gallery"),y=document.querySelector(".form"),p=y.elements[0];p.classList.add("input");const M=y.elements[1];M.classList.add("button");const R=document.querySelector(".load-more-btn");let l=null,f=null,i=null;y.addEventListener("submit",P);async function P(e){if(e.preventDefault(),B(m),u(),b(),i=p.value,l=1,i===""){d(),n.error({message:"Write your something you want to see",position:"topRight"});return}try{const t=await g(i,l);if(t.data.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),u();return}else{h(m,t.data.hits);let r=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r.height*2,behavior:"smooth"}),f=Math.ceil(t.data.totalHits/15),l<f?L():n.info({position:"bottomCenter",message:"We're sorry, but you've reached the end of search results."})}}catch{n.error({message:"Bad request",position:"topRight"});return}d(),p.value=""}R.addEventListener("click",$);async function $(e){e.preventDefault(),u(),b(),l+=1;try{const t=await g(i,l);h(m,t.data.hits);let r=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r.height*2,behavior:"smooth"}),l<f?L():n.info({position:"bottomCenter",message:"We're sorry, but you've reached the end of search results."})}catch{n.error({message:"Bad request",position:"topRight"});return}d()}
//# sourceMappingURL=index.js.map
